name: Spell Check

on:
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.md'
      - '**/*.json'
      - '**/*.yml'
      - '**/*.yaml'

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run cspell
        uses: streetsidesoftware/cspell-action@v2
        with:
          config: .cspell.json
          inline: warning
